[package]
name = "iptables_manager"
version = "0.1.0"
edition = "2021"
description = "A tool for managing iptables rules and capturing network traffic."

[dependencies]
clap = "4.5.4"
pcap = "1.3.0"
pnet_packet = "0.34.0"
iptables = "0.5.1"
